import UnitIcon from './UnitIcon.jsx';
export default function CommandPanel({game,dispatch}) {
  const u=game.units.find(u=>u.id===game.selectedId&&u.hp>0),locked=game.turn!=='blue'||!!game.winner;
  return <aside>
    <section className="phase-panel"><div className="eyebrow">COMMAND PHASE <span>{String(game.turnNumber).padStart(2,'0')}</span></div><h2><span className="live-dot"/>{game.winner?'行动结束':locked?'敌方行动阶段':'我方行动阶段'}</h2><p>{locked&&!game.winner?`侦听敌方动向 · ${game.enemyIndex} / ${game.enemyQueue.length}`:'每车移动、开火各一次；维修占用开火。'}</p><button className="primary" id="end-turn" disabled={locked} onClick={()=>dispatch({type:'END_TURN'})}>结束回合 <span>→</span></button></section>
    <section className="unit-panel"><div className="section-title">车辆情报 <span>{u?`UNIT ${String(u.id).padStart(2,'0')}`:'待命'}</span></div>
      {u?<><div className="unit-header"><div className="unit-art"><UnitIcon type={u.type}/></div><div><div className="unit-name">{u.name} <small>{String(u.id).padStart(2,'0')}</small></div><div className="unit-sub">{u.label}</div></div></div><div className="hp-row"><span>装甲完整度</span><span>{u.hp} / {u.maxHp}</span></div><div className="hp-track"><div className="hp-fill" style={{width:`${u.hp/u.maxHp*100}%`}}/></div><div className="unit-stats">{[['移动',u.move],['射程',`${u.minRange}–${u.range}`],['火力',u.attack],['视野',u.vision],['装甲',u.armor]].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</div><p className="unit-description">{u.description}</p><div className="modes"><button id="move-mode" className={game.mode==='move'?'active':''} disabled={locked||u.moved} onClick={()=>dispatch({type:'MODE',mode:'move'})}>{u.moved?'✓ 已移动':'◇ 移动'}</button><button id="attack-mode" className={game.mode==='attack'?'active':''} disabled={locked||u.fired} onClick={()=>dispatch({type:'MODE',mode:'attack'})}>{u.fired?'✓ 已行动':'⌖ 开火'}</button>{u.repair>0&&<button id="repair-mode" className={game.mode==='repair'?'active':''} disabled={locked||u.fired} onClick={()=>dispatch({type:'MODE',mode:'repair'})}>✚ 维修</button>}</div></>:<div className="empty-selection"><span>⌖</span>选择我方车辆以查看情报</div>}
    </section>
    <section className="squad-panel"><div className="section-title">作战编队 <span>9 VEHICLES</span></div><div id="squad">{game.units.filter(a=>a.team==='blue').map(a=><button key={a.id} className={`squad-row ${a.id===u?.id?'active':''} ${a.hp<=0?'dead':''}`} disabled={a.hp<=0||locked} onClick={()=>dispatch({type:'SELECT',id:a.id})} data-unit={a.id}><UnitIcon type={a.type}/><span>{String(a.id).padStart(2,'0')} &nbsp; {a.name}</span><small>{a.hp<=0?'已损失':a.moved&&a.fired?'行动完毕':a.moved?'已移动':a.fired?'已行动':'待命'} · {a.hp}</small></button>)}</div></section>
    <section className="log-panel"><div className="section-title">战场通讯 <span className="live-label">● LIVE</span></div><div id="log" aria-live="polite">{game.logs.map(l=><div key={l.id} className={`log-entry ${l.kind}`}><time>{String(l.round).padStart(2,'0')} ›</time>{l.message}</div>)}</div></section>
  </aside>;
}
